import { train, type TeamManual } from "@/content/manuals";

const BOX = [
  "raichu-mega-y",
  "rillaboom",
  "sneasler",
  "gholdengo",
  "arcanine-hisui",
  "sylveon",
] as const;

const PACK_A = "pack-tempo";
const PACK_B = "pack-mixed-scale";
const PACK_C = "pack-four-cannon";
const PACK_D = "pack-tempo-physical";
const PACK_E = "pack-four-converter";
const PACK_F = "pack-control";

const SP_NOTE =
  "Starting architecture spend (66 SP, max 32). Not claimed as damage-calced for every M-C threshold.";

export const ARCHITECTURE_C_NETWORK_TEMPO_MANUAL = {
  id: "architecture-c-network-tempo-manual",
  title: "Architecture C — Network Tempo",
  lede: "Fake Out opens turns. Partners convert them. Multiple endgames, not one linear core.",
  format: "doubles",
  philosophy:
    "Not a Raichu team, not a Fake Out team, not a Gholdengo team. A network-tempo team: manufacture turns where one Pokémon creates an opening and another converts it into permanent advantage.",
  archetype: "balance",
  family: "clock",
  meta: "Champions Doubles, Regulation M-C. Working build around the architecture — validate SP against exact thresholds later.",
  setsNote: SP_NOTE,
  press: ["Tempo", "Position", "Convert", "Multiple endgames"],
  pilot: {
    thesis:
      "Can we repeatedly manufacture turns in which one Pokémon creates an opening and another converts that opening into permanent advantage?",
    rule: "Play the four that manufacture the game state you need — not your favorite six.",
    fail: "Treating all six as equally important every game.",
  },
  box: [...BOX],
  core: ["raichu-mega-y", "rillaboom", "sneasler", "gholdengo"],
  slugs: ["raichu-mega-y", "rillaboom", "sneasler", "gholdengo"],
  slots: [],
  phases: [],
  loops: [],
  hazards: [],
  commandments: [
    "Don't waste Fake Out — it should create something.",
    "Don't expose Gholdengo without a reason — its value compounds.",
    "Use Rillaboom as a pivot, not just a Grass attacker.",
    "Don't reveal Sneasler's entire role immediately.",
    "Don't force the same four Pokémon every game.",
  ],
  architecture: [
    {
      title: "Tempo",
      body: "Infrastructure that manufactures free turns.",
      slugs: ["raichu-mega-y", "rillaboom", "sneasler"],
    },
    {
      title: "Converters",
      body: "Scaling pieces that spend the free turn.",
      slugs: ["gholdengo", "arcanine-hisui"],
    },
    {
      title: "Fallback",
      body: "Independent special endgame.",
      slugs: ["sylveon"],
    },
  ],
  engines: [
    {
      id: "wc-nasty-plot",
      label: "Nasty Plot Gholdengo",
      path: ["Fake Out", "Nasty Plot", "Make It Rain"],
      how: "Fake Out creates the setup turn. Nasty Plot creates the conversion. Make It Rain spends it.",
      dependsOn: "A Fake Out partner on the field",
      fallback: "Preserve Gholdengo and find the setup later",
    },
    {
      id: "wc-coaching-arcanine",
      label: "Coaching H-Arcanine",
      path: ["Coaching", "Head Smash / Flare Blitz", "Extreme Speed"],
      how: "Sneasler converts into support. H-Arcanine becomes the hammer.",
      dependsOn: "Sneasler + H-Arcanine together",
    },
    {
      id: "wc-unburden",
      label: "Unburden Sneasler",
      path: ["Close Combat", "White Herb", "Unburden", "Cleanup"],
      how: "Preserve White Herb until the decisive phase — Unburden is a timed resource.",
    },
    {
      id: "wc-rilla-attrition",
      label: "Rillaboom attrition",
      path: ["Fake Out", "U-turn", "Terrain", "Repeat"],
      how: "Slow win: reposition, recover, Fake Out again. Rillaboom is allowed to only pivot.",
    },
    {
      id: "wc-sylveon",
      label: "Sylveon endgame",
      path: ["Hyper Voice", "Hyper Voice / Hyper Beam", "Quick Attack"],
      how: "Independent fallback once Fairy answers are gone. Reliable spread, not setup amplification.",
    },
  ],
  network: {
    thesis: "A creates a resource that B converts.",
    edges: [
      {
        from: "raichu-mega-y",
        to: "gholdengo",
        creates: "Fake Out free turn",
        converts: "Nasty Plot",
        engineId: "wc-nasty-plot",
      },
      {
        from: "rillaboom",
        to: "gholdengo",
        creates: "Fake Out free turn",
        converts: "Nasty Plot",
        engineId: "wc-nasty-plot",
      },
      {
        from: "sneasler",
        to: "gholdengo",
        creates: "Threat density",
        converts: "Setup window",
        engineId: "wc-nasty-plot",
      },
      {
        from: "sneasler",
        to: "arcanine-hisui",
        creates: "Coaching",
        converts: "Scaled physical damage",
        engineId: "wc-coaching-arcanine",
      },
      {
        from: "rillaboom",
        to: "arcanine-hisui",
        creates: "Fake Out → U-turn",
        converts: "Attack window",
      },
      {
        from: "raichu-mega-y",
        to: "arcanine-hisui",
        creates: "Fake Out",
        converts: "Free attack turn",
      },
      {
        from: "raichu-mega-y",
        to: "rillaboom",
        creates: "Lightning Rod + Fake Out",
        converts: "Terrain positioning",
      },
      {
        from: "rillaboom",
        to: "sneasler",
        creates: "Fake Out / U-turn",
        converts: "Immediate threat entry",
        engineId: "wc-unburden",
      },
      {
        from: "sylveon",
        to: "gholdengo",
        creates: "Fairy pressure cost",
        converts: "Freer positioning for partners",
        engineId: "wc-sylveon",
      },
    ],
  },
  controlPlanes: [
    {
      id: "fake-out",
      label: "Fake Out",
      setterSlug: "raichu-mega-y",
      effect: "Guaranteed interruption → one free decision",
      whoBenefits: "Anyone needing a setup or attack turn",
    },
    {
      id: "grassy",
      label: "Grassy Terrain",
      setterSlug: "rillaboom",
      effect: "Recovery, Grass boost, Ground soften",
      whoBenefits: "The whole board's longevity",
    },
    {
      id: "coaching",
      label: "Coaching",
      setterSlug: "sneasler",
      effect: "Attack + Defense boost to partner",
      whoBenefits: "H-Arcanine, Rillaboom",
    },
    {
      id: "unburden",
      label: "Unburden",
      setterSlug: "sneasler",
      effect: "Speed spike after White Herb",
      whoBenefits: "Sneasler as endgame cleaner",
    },
  ],
  matchupScripts: [
    {
      id: "rain",
      foe: "Rain",
      why: "Attack rain infrastructure — don't overwrite weather. Bench H-Arcanine.",
      packId: PACK_A,
      sequence: {
        title: "Anti-rain",
        beats: [
          { slug: "raichu-mega-y", click: "Pressure Pelipper", why: "Zap Cannon / Fake Out" },
          { slug: "rillaboom", click: "Pressure Water", why: "Wood Hammer / Glide" },
          { slug: "sneasler", click: "Pressure Archaludon", why: "Close Combat" },
          { slug: "gholdengo", click: "General pressure", why: "Setup when safe" },
        ],
      },
    },
    {
      id: "physical-heavy",
      foe: "Physical-heavy",
      why: "Mixed scaling: Coaching H-Arcanine + Nasty Plot Gholdengo.",
      packId: PACK_B,
      sequence: {
        beats: [
          { slug: "sneasler", click: "Coaching or Fake Out" },
          { slug: "arcanine-hisui", click: "Convert" },
        ],
      },
    },
    {
      id: "fragile",
      foe: "Fragile offense",
      why: "Maximum Fake Out + Sylveon attrition. No need for both converters.",
      packId: PACK_F,
      sequence: {
        beats: [{ click: "Fake Out → Fake Out → position → priority" }],
      },
    },
  ],
  megaPool: {
    rule: "One Mega Evolution per battle.",
    previewPressure:
      "Default is Mega Raichu Y. Mega Staraptor is an experiment — only useful if Staraptor is good enough without Mega.",
    candidates: [
      {
        slug: "raichu-mega-y",
        stone: "Raichunite Y",
        when: "Default Network Tempo game",
      },
      {
        slug: "staraptor-mega",
        stone: "Staraptite",
        when: "Experimental Tailwind / Intimidate package — treat as later test",
      },
    ],
  },
  construction: {
    thesis: "Network Tempo: tempo → position → conversion → multiple endgames.",
    method: "Build around overlapping Fake Out engines and independent converters, not a single linear core.",
    winCondition: "Manufacture free turns; convert them with Gholdengo or H-Arcanine; Sylveon as fallback.",
    endgames: [
      { id: "wc-nasty-plot", label: "Nasty Plot Gholdengo", path: "gholdengo", how: "Setup → Make It Rain" },
      {
        id: "wc-coaching-arcanine",
        label: "Coaching H-Arcanine",
        path: "arcanine-hisui",
        how: "Coaching → nuke → Extreme Speed",
      },
      { id: "wc-sylveon", label: "Sylveon endgame", path: "sylveon", how: "Spread Fairy cleanup" },
    ],
    altSlots: [
      {
        slug: "staraptor",
        insteadOf: "sylveon",
        why: "Intimidate + Tailwind + U-turn. Shifts the architecture toward speed control.",
        answers: "Speed-advantaged boards, physical-heavy matchups",
        costs: "Loses independent Fairy endgame",
      },
    ],
  },
  ledger: {
    dropped: {
      slug: "linear-core",
      lost: ["Single win-condition dependency", "One-node collapse when the star dies"],
    },
    gained: [
      "Three Fake Out nodes",
      "Two damage-type converters",
      "Independent Fairy fallback",
    ],
    laterTests: [
      {
        slug: "kingambit",
        change: "Try as sideboard physical scaler with Sneasler Coaching",
        whenToTest: "After the core six is validated — raises physical concentration",
      },
      {
        slug: "sylveon",
        change: "Optimize Modest bulk/SpA split via damage tests",
        whenToTest: "First experimental variable on the six",
      },
      {
        slug: "rillaboom",
        change: "Revisit 2 Def leftover allocation",
        whenToTest: "Once pivot role is confirmed in ladder games",
      },
    ],
  },
  roster: [
    {
      slug: "raichu-mega-y",
      title: "Mega Raichu Y",
      job: "speed",
      literacy: "disruptor",
      role: "Tempo engine",
      primaryJob: "Tempo engine",
      ability: "Lightning Rod",
      abilityStages: {
        before: "Lightning Rod",
        after: "No Guard",
        when: "After Mega Evolution",
      },
      item: "Raichunite Y",
      itemWhy: "Default Mega slot for Architecture C.",
      nature: "Timid",
      training: train(32, 0, 11, 0, 0, 23, {
        label: "Timid defensive-speed",
        why: "Survive to generate tempo. Offensive power comes from Mega stats and No Guard, not SpA investment.",
        spend: ["32 HP", "11 Def", "23 Spe"],
        rule: SP_NOTE,
      }),
      moves: [
        { name: "Fake Out", why: "Guaranteed interruption → one free decision for the partner." },
        { name: "Zap Cannon", why: "No Guard signature — Electric nuke + paralysis." },
        { name: "Focus Blast", why: "Steel / Dark / Rock coverage." },
        { name: "Protect", why: "Information + wasted opponent action + reposition." },
      ],
      objective: "Threat generator — not a Fake Out bot.",
      howToPlay: "Ask whether the opponent can KO Gholdengo, ignore it, or needs Lightning Rod punished before auto-Fake Outing.",
      gives: ["tempo", "Lightning Rod"],
      answers: ["Electric targeting", "Water / Flying"],
      networkJobs: {
        creates: "tempo",
        converts: "special damage",
        protects: "partners via Lightning Rod",
      },
      opening: [
        { ask: "Can they immediately KO Gholdengo?", then: "Fake Out / Protect / reposition." },
        { ask: "Can they safely ignore Gholdengo?", then: "Let it Nasty Plot." },
        { ask: "Dangerous Electric target on their side?", then: "Lightning Rod already changes options." },
        { ask: "Can Raichu score meaningful damage?", then: "Zap Cannon." },
        { ask: "Steel / Dark / Rock threatening?", then: "Focus Blast." },
      ],
    },
    {
      slug: "rillaboom",
      title: "Rillaboom",
      job: "support",
      literacy: "pivot",
      role: "Positioning engine",
      primaryJob: "Positioning engine",
      ability: "Grassy Surge",
      item: "Assault Vest",
      itemWhy: "Resilient pivot that repeatedly re-enters.",
      nature: "Adamant",
      training: train(32, 32, 2, 0, 0, 0, {
        label: "Adamant durable pivot",
        why: "Durable physical pivot — not the speed-control Pokémon.",
        spend: ["32 HP", "32 Atk", "2 Def"],
        rule: SP_NOTE,
      }),
      moves: [
        { name: "Fake Out", why: "Second Fake Out node — opponent cannot treat it as a one-time gimmick." },
        { name: "U-turn", why: "Board-state reset when they Protect or the seat is wrong." },
        { name: "Wood Hammer", why: "Real Grass damage, not just support." },
        { name: "Grassy Glide", why: "Priority cleanup and independent endgame." },
      ],
      objective: "Shape the battlefield. Allowed to only reposition.",
      howToPlay: "Fake Out when it creates a winning setup turn. U-turn when they Protect or the board turns.",
      gives: ["terrain", "Fake Out", "U-turn"],
      networkJobs: {
        creates: "terrain / tempo",
        converts: "physical damage",
        protects: "board via Fake Out",
        scales: "attrition",
        repositions: "U-turn",
      },
      opening: [
        { ask: "Can Fake Out create a winning setup turn?", then: "Fake Out." },
        { ask: "Likely to Protect?", then: "U-turn may be better." },
        { ask: "Weak to Grass?", then: "Attack." },
        { ask: "Board becoming unfavorable?", then: "U-turn." },
      ],
    },
    {
      slug: "sneasler",
      title: "Sneasler",
      job: "breaker",
      literacy: "disruptor",
      role: "Connector",
      primaryJob: "Connector",
      ability: "Unburden",
      item: "White Herb",
      itemWhy: "Clears Close Combat drops, then activates Unburden — damage protection + speed.",
      nature: "Jolly",
      training: train(2, 32, 0, 0, 0, 32, {
        label: "Jolly max offense",
        why: "Hit as hard as possible + become as fast as possible.",
        spend: ["2 HP", "32 Atk", "32 Spe"],
        rule: SP_NOTE,
      }),
      moves: [
        { name: "Fake Out", why: "Third tempo button." },
        { name: "Close Combat", why: "Primary damage + White Herb trigger." },
        { name: "Dire Claw", why: "Status chaos while staying offensive." },
        { name: "Coaching", why: "Turns Sneasler into a network connector for H-Arcanine / Rillaboom." },
      ],
      objective: "Swiss Army knife — change roles in the same game.",
      howToPlay: "Preserve White Herb until the decisive phase. Make them wonder which button you press.",
      gives: ["Fake Out", "Coaching", "Unburden"],
      ampTargets: [
        { slug: "arcanine-hisui", becomes: "Scaled physical hammer" },
        { slug: "rillaboom", becomes: "Stronger physical board" },
      ],
      itemLoop: {
        title: "White Herb Unburden",
        beats: [
          { click: "Close Combat", why: "Damage + Def/SpD drops" },
          { click: "White Herb activates", why: "Drops cleared, item gone" },
          { click: "Unburden", why: "Speed controller" },
        ],
      },
      networkJobs: {
        creates: "tempo",
        converts: "physical damage",
        protects: "setup partners",
        scales: "Coaching",
      },
      opening: [
        { ask: "Need immediate disruption?", then: "Fake Out." },
        { ask: "Can I KO something?", then: "Close Combat." },
        { ask: "Status swing available?", then: "Dire Claw." },
        { ask: "H-Arcanine ready to become terrifying?", then: "Coaching." },
        { ask: "Need speed later?", then: "Preserve White Herb." },
      ],
    },
    {
      slug: "gholdengo",
      title: "Gholdengo",
      job: "breaker",
      literacy: "sweeper",
      role: "Special win condition",
      primaryJob: "Special win condition",
      ability: "Good as Gold",
      item: "Life Orb",
      itemWhy: "Maximum conversion after one setup turn.",
      nature: "Timid",
      training: train(
        2,
        0,
        0,
        32,
        0,
        32,
        {
          label: "Timid max SpA / Spe",
          why: "Maximum special damage + conversion reliability. Prefer Timid over Modest for this architecture.",
          spend: ["2 HP", "32 SpA", "32 Spe"],
          rule: SP_NOTE,
        },
        [
          {
            name: "Modest bulky",
            sp: { hp: 17, atk: 0, def: 0, spa: 17, spd: 0, spe: 32 },
            why: "Ladder-common alternative — less preferred here.",
          },
        ],
      ),
      moves: [
        { name: "Nasty Plot", why: "Win-condition switch — threat becomes the board's central problem." },
        { name: "Make It Rain", why: "Spends the setup into overwhelming damage." },
        { name: "Shadow Ball", why: "Single-target vs Steel-resistant hides." },
        { name: "Protect", why: "Survives the double-target and revenge turns it attracts." },
      ],
      objective: "Low-dependency win condition. Can still win if tempo pieces die.",
      howToPlay: "Early: preserve. Mid: find setup. Endgame: stop being clever and attack.",
      gives: ["setup conversion", "status ignore"],
      networkJobs: {
        creates: "setup threat",
        converts: "special damage",
        protects: "itself via Protect / typing",
        scales: "Nasty Plot",
      },
    },
    {
      slug: "arcanine-hisui",
      title: "Hisuian Arcanine",
      job: "breaker",
      literacy: "wallbreaker",
      role: "Physical converter",
      primaryJob: "Physical converter",
      ability: "Rock Head",
      item: "Focus Sash",
      itemWhy: "Guarantees one meaningful exchange on a frail hammer.",
      nature: "Jolly",
      training: train(2, 32, 0, 0, 0, 32, {
        label: "Jolly max offense",
        why: "Matches dominant competitive direction — explosive first exchange.",
        spend: ["2 HP", "32 Atk", "32 Spe"],
        rule: SP_NOTE,
      }),
      moves: [
        { name: "Head Smash", why: "The nuke — Rock Head makes it safer." },
        { name: "Flare Blitz", why: "Reliable Fire STAB." },
        { name: "Extreme Speed", why: "Finish without winning the speed war." },
        { name: "Protect", why: "Survives the attention it attracts." },
      ],
      objective: "One-time explosive resource. Trade for something important.",
      howToPlay: "Don't waste the Sash exchange. Extreme Speed is the second life.",
      gives: ["physical nuke", "priority"],
      answers: ["Steel", "Fire answers"],
      networkJobs: {
        creates: "immediate threat",
        converts: "physical damage",
        protects: "itself via Sash",
      },
    },
    {
      slug: "sylveon",
      title: "Sylveon",
      job: "breaker",
      literacy: "sweeper",
      role: "Independent special converter",
      primaryJob: "Independent special converter",
      ability: "Pixilate",
      item: "Fairy Feather",
      itemWhy: "Amplifies the Fairy purpose.",
      nature: "Modest",
      training: train(32, 0, 25, 9, 0, 0, {
        label: "Modest bulky",
        why: "Survive and repeatedly produce spread damage — not another glass cannon. First spread to optimize.",
        spend: ["32 HP", "25 Def", "9 SpA"],
        rule: SP_NOTE,
      }),
      lock: "later-test",
      lockWhy: "First experimental variable — bulk vs SpA via damage testing.",
      moves: [
        { name: "Hyper Voice", why: "Default Pixilate spread — no need to pick the right target." },
        { name: "Hyper Beam", why: "Nuclear late-game option." },
        { name: "Quick Attack", why: "Priority cleanup." },
        { name: "Detect", why: "Preservation." },
      ],
      objective: "Simplification tool. As the board shrinks, spread damage gets stronger.",
      howToPlay: "Early: establish control. Mid: remove Fairy answers. Late: Hyper Voice.",
      gives: ["Fairy spread", "late-game"],
      networkJobs: {
        creates: "Fairy pressure",
        converts: "spread damage",
        protects: "itself via bulk",
        scales: "late-game",
      },
    },
  ],
  packs: [
    {
      id: PACK_A,
      label: "Package A",
      when: "General unknown / rain / baseline",
      identity: "Maximum tempo",
      slugs: ["raichu-mega-y", "rillaboom", "sneasler", "gholdengo"],
      engineIds: ["wc-nasty-plot", "wc-unburden", "wc-rilla-attrition"],
      endgameIds: ["wc-nasty-plot"],
      strategy: {
        opponentPattern: "Unknown or rain-leaning board",
        bring: ["raichu-mega-y", "rillaboom", "sneasler", "gholdengo"],
        purpose: "Maximum Fake Out infrastructure into Nasty Plot conversion.",
        targets: ["Fragile setup", "Rain infrastructure", "Slow special cores"],
        refuses: ["Boards that punish all three Fake Out users hard"],
        winCondition: "Fake Out → Nasty Plot → Make It Rain",
        mantra: "Three Fake Outs. One setup. Convert.",
        gamePlan: "Tempo → Setup → Convert",
      },
      loops: [
        {
          title: "Fake Out → Nasty Plot",
          body: "Any of Raichu / Rillaboom / Sneasler Fake Outs → Gholdengo Nasty Plots.",
        },
      ],
      flows: [
        {
          id: "pack-a-lead",
          title: "Opening",
          forks: [
            {
              id: "setup-free",
              when: "They cannot KO Gholdengo through Fake Out",
              then: "Fake Out + Nasty Plot",
            },
            {
              id: "protect-expect",
              when: "They look ready to Protect the Make It Rain",
              then: "Protect / U-turn instead — spend their defensive resource",
            },
          ],
        },
      ],
      hazards: [],
    },
    {
      id: PACK_B,
      label: "Package B",
      when: "Physical-heavy opponent",
      identity: "Mixed scaling",
      slugs: ["rillaboom", "sneasler", "arcanine-hisui", "gholdengo"],
      engineIds: ["wc-coaching-arcanine", "wc-nasty-plot", "wc-rilla-attrition"],
      endgameIds: ["wc-coaching-arcanine", "wc-nasty-plot"],
      strategy: {
        opponentPattern: "Physical-leaning pressure",
        bring: ["rillaboom", "sneasler", "arcanine-hisui", "gholdengo"],
        purpose: "Two scaling threats of different damage types plus Rillaboom positioning.",
        targets: ["Physical walls you can Coaching past", "Boards weak to mixed damage"],
        refuses: ["Heavy Intimidate stacks without answers"],
        winCondition: "Coaching H-Arcanine or Nasty Plot Gholdengo",
        mantra: "Physical scale and special scale at once.",
      },
      loops: [
        {
          title: "Coaching → H-Arcanine",
          body: "Sneasler Coaches → H-Arcanine Head Smash / Flare Blitz → Extreme Speed.",
        },
      ],
      flows: [],
      hazards: [],
    },
    {
      id: PACK_C,
      label: "Package C",
      when: "Structurally vulnerable to raw offense",
      identity: "Four-cannon",
      slugs: ["raichu-mega-y", "arcanine-hisui", "sylveon", "gholdengo"],
      engineIds: ["wc-nasty-plot", "wc-sylveon"],
      endgameIds: ["wc-nasty-plot", "wc-sylveon"],
      strategy: {
        opponentPattern: "Soft to raw offensive pressure",
        bring: ["raichu-mega-y", "arcanine-hisui", "sylveon", "gholdengo"],
        purpose: "Special pressure, physical nuke, special scale, Fairy spread — four damage axes.",
        targets: ["Fragile offense", "Fairy-vulnerable boards"],
        refuses: ["Need maximum Fake Out infrastructure"],
        winCondition: "Overwhelm with multiple damage types",
        mantra: "Four cannons. Pick the axis they can't answer.",
      },
      loops: [],
      flows: [],
      hazards: [],
    },
    {
      id: PACK_D,
      label: "Package D",
      when: "Need tempo + physical pressure",
      identity: "Tempo + physical",
      slugs: ["raichu-mega-y", "rillaboom", "arcanine-hisui", "sylveon"],
      engineIds: ["wc-rilla-attrition", "wc-sylveon"],
      endgameIds: ["wc-sylveon"],
      strategy: {
        opponentPattern: "Needs Fake Out + Extreme Speed + Fairy without Gholdengo",
        bring: ["raichu-mega-y", "rillaboom", "arcanine-hisui", "sylveon"],
        purpose: "Hard to remove every piece efficiently — priority and terrain.",
        targets: ["Boards that fold to priority and spread"],
        refuses: ["Need Nasty Plot conversion specifically"],
        winCondition: "Attrition into Sylveon / Extreme Speed",
        mantra: "Tempo, terrain, priority, Fairy.",
      },
      loops: [],
      flows: [],
      hazards: [],
    },
    {
      id: PACK_E,
      label: "Package E",
      when: "Don't need maximum tempo",
      identity: "Four-converter",
      slugs: ["sneasler", "gholdengo", "arcanine-hisui", "sylveon"],
      engineIds: ["wc-coaching-arcanine", "wc-nasty-plot", "wc-sylveon", "wc-unburden"],
      endgameIds: ["wc-nasty-plot", "wc-coaching-arcanine", "wc-sylveon"],
      strategy: {
        opponentPattern: "Every mon on the field should be a different damage axis",
        bring: ["sneasler", "gholdengo", "arcanine-hisui", "sylveon"],
        purpose: "Four converters — less Fake Out density, more endgame axes.",
        targets: ["Slow bulky teams"],
        refuses: ["Need three Fake Outs to open"],
        winCondition: "Any of the four conversion paths",
        mantra: "Every seat is a different problem.",
      },
      loops: [],
      flows: [],
      hazards: [],
    },
    {
      id: PACK_F,
      label: "Package F",
      when: "Fragile setup / control game",
      identity: "Control",
      slugs: ["raichu-mega-y", "rillaboom", "sneasler", "sylveon"],
      engineIds: ["wc-rilla-attrition", "wc-sylveon", "wc-unburden"],
      endgameIds: ["wc-sylveon"],
      strategy: {
        opponentPattern: "Relies on fragile setup",
        bring: ["raichu-mega-y", "rillaboom", "sneasler", "sylveon"],
        purpose: "No Gholdengo, no H-Arcanine — Fake Out → Fake Out → position → priority → attrition.",
        targets: ["Fragile setup teams"],
        refuses: ["Need a hard scaling converter immediately"],
        winCondition: "Control into Sylveon endgame",
        mantra: "Three Fake Outs. No greed. Attrition.",
      },
      loops: [
        {
          title: "Triple Fake Out attrition",
          body: "Fake Out → Fake Out → Fake Out → positioning → priority → Hyper Voice.",
        },
      ],
      flows: [],
      hazards: [],
    },
  ],
} satisfies TeamManual;
