import type { Lesson } from "@/content/curriculum";

/** Great Ball item reference — hold items that decide Champions singles sets. */
export const ITEMS_LESSON: Lesson = {
  slug: "training",
  band: "great-ball",
  title: "Items that decide the set",
  thesis:
    "Sash lives one hit. Sitrus stays. Choice locks power. The Mega stone is the wincon. Read the item before you read the species.",
  skipIf: "Skip if you already know why Sash Cott is not Sitrus Corvi, and why Specs is not Leftovers.",
  body: [
    "In Champions singles the held item is half the set. Same Corviknight with Rocky Helmet vs Leftovers vs Boots plays three different games. Learn each item as Does · When · Answer — then scout it on preview.",
    "Stat Points still matter (66 total, max 32) — that lives on the Speed and jobs pages. This page is only what they hold.",
  ],
  rules: [
    { label: "Live", detail: "Focus Sash — one guaranteed survive from full." },
    { label: "Stay", detail: "Sitrus Berry, Leftovers — HP to remain in the slot." },
    { label: "Lock", detail: "Choice Scarf / Band / Specs — power or Speed, one move." },
    { label: "Tax", detail: "Life Orb, Rocky Helmet — damage in, damage back." },
    { label: "Bulk", detail: "Assault Vest — special wall that cannot status." },
    { label: "Stone", detail: "Mega stone — the item slot IS the Omni Ring wincon." },
  ],
  beats: [
    {
      title: "Focus Sash",
      tag: "One live",
      body: "If you are at full HP, Sash leaves you at 1 HP instead of fainting to any single hit (OHKO moves and some effects still ignore it). After it pops you are glass. Standard on fragile leads and Tailwind setters that must live Fake Out. Hazards, chip, and prior damage mean Sash never triggers — Heavy-Duty Boots pair matters on hazard-heavy threes.",
      takeaway: "Sash is for glass that must act once. Do not put it on a wall that wants to stay.",
      rows: [
        { label: "Does", detail: "Survives any one hit from full HP at 1 HP. Then gone." },
        { label: "When", detail: "Cott / HO leads. Live Fake Out then Tailwind or a revenge KO. Fragile cleaners that must click once." },
        { label: "Answer", detail: "Chip with rocks, Fake Out, or a weak hit first. Double into the 1 HP. Knock Off before the critical turn if you can." },
      ],
      example: { slug: "whimsicott", caption: "Sash lives Fake Out. Then Tailwind." },
      examples: [
        { slug: "whimsicott", caption: "Sash clock" },
        { slug: "garchomp", caption: "Sash revenge / lead" },
        { slug: "glimmora", caption: "Sash hazards lead" },
        { slug: "greninja", caption: "Sash Protean" },
      ],
    },
    {
      title: "Sitrus Berry",
      tag: "Burst heal",
      body: "When HP drops to half or below, Sitrus heals 25% once. It is a second HP bar for Pokémon that stay and trade — walls, pivots, Unburden users that pop the berry on purpose. Unlike Leftovers it is one burst, not a drip. Knock Off removes it before it can heal.",
      takeaway: "Sitrus on stay Pokémon. Sash on glass. Do not confuse the two.",
      rows: [
        { label: "Does", detail: "One-time heal (~25%) when you drop to ≤50% HP." },
        { label: "When", detail: "Corvi / Rotom / Primarina stays. Unburden (Sneasler) pops berry to double Speed." },
        { label: "Answer", detail: "Knock Off before they dip to half. Chip past the heal window. Status so the stay loses anyway." },
      ],
      example: { slug: "corviknight", caption: "Sitrus stay. The shield keeps the slot." },
      examples: [
        { slug: "corviknight", caption: "Sitrus shield" },
        { slug: "rotom-wash", caption: "Sitrus pivot" },
        { slug: "primarina", caption: "Sitrus special wall" },
        { slug: "sneasler", caption: "Sitrus Unburden" },
      ],
    },
    {
      title: "Leftovers",
      tag: "Passive heal",
      body: "Heals a little HP every turn. The classic wall item — Hippowdon, Aegislash, Toxapex loops. Worse than Sitrus for surviving one big hit; better for winning long stalls and repeated switches. Knock Off deletes the drip forever.",
      takeaway: "Leftovers wins long games. Against it: Knock Off early, then break.",
      rows: [
        { label: "Does", detail: "Residual HP recovery each turn while held." },
        { label: "When", detail: "Fat pivots and stall walls that Roost / Slack Off / Recover." },
        { label: "Answer", detail: "Knock Off. Taunt. Toxic. Pressure so they never get free Leftovers turns." },
      ],
      example: { slug: "dondozo", caption: "Leftovers Unaware wall. The drip is the plan." },
      examples: [
        { slug: "dondozo", caption: "Leftovers" },
        { slug: "aegislash-shield", caption: "Leftovers stance" },
        { slug: "toxapex", caption: "Leftovers stall" },
        { slug: "skeledirge", caption: "Leftovers Unaware" },
      ],
    },
    {
      title: "Choice Scarf",
      tag: "Speed lock",
      body: "Boosts Speed but locks you into the first move you click until you switch. Scarf is how medium bases outrun the format without Tailwind. Protect and predicted switches punish the lock. You cannot Protect while Choice-locked.",
      takeaway: "Scarf wins the race you packed it for. Into a predicted lock: switch or Protect — they donated a turn.",
      rows: [
        { label: "Does", detail: "≈1.5× Speed. Locks into one move until switch." },
        { label: "When", detail: "Revenge cleaners. Outrun medium Speed without a clock. Choice Meowscarada / Cinderace lines." },
        { label: "Answer", detail: "Force a bad lock with a resist. Protect. Switch on the locked move. Trick Room ignores Scarf Speed." },
      ],
      example: { slug: "meowscarada", caption: "Scarf U-turn / Flower Trick revenge." },
      examples: [
        { slug: "meowscarada", caption: "Choice Scarf" },
        { slug: "cinderace", caption: "Scarf Libero" },
        { slug: "gholdengo", caption: "Scarf Make It Rain" },
      ],
    },
    {
      title: "Choice Band · Choice Specs",
      tag: "Power lock",
      body: "Band boosts Attack; Specs boost Special Attack. Same lock as Scarf — one move until you leave. Specs Primarina and Band Kingambit / Meowscarada turn coverage into OHKOs. The lock is the cost: wrong click into a resist is a free switch for them.",
      takeaway: "Choice power is a prediction tax. Scout with Protect, then punish the lock.",
      rows: [
        { label: "Does", detail: "≈1.5× Atk (Band) or SpA (Specs). Move-locked until switch." },
        { label: "When", detail: "Wallbreakers that must OHKO. Specs specials that delete physical walls." },
        { label: "Answer", detail: "Resist the locked STAB. Protect to scout. Switch into the lock. Do not stay a check that dies to the locked move." },
      ],
      example: { slug: "primarina", caption: "Specs Moonblast. Physical walls are unsafe." },
      examples: [
        { slug: "primarina", caption: "Choice Specs" },
        { slug: "kingambit", caption: "Choice Band" },
        { slug: "meowscarada", caption: "Band Flower Trick" },
        { slug: "gholdengo", caption: "Specs / Band lines" },
      ],
    },
    {
      title: "Life Orb",
      tag: "Flex power",
      body: "Boosts damage on every attack and chips your own HP each hit. No lock — you keep Protect, coverage, and pivots. Standard on freer attackers that need KO numbers without Choice. Residual plus rocks pops Multiscale and Sash on both sides.",
      takeaway: "Life Orb is Choice power without the lock. Chip yourself carefully under hazards.",
      rows: [
        { label: "Does", detail: "≈1.3× damage on attacks; self-chip each hit." },
        { label: "When", detail: "Setup sweepers and revenge attackers that need flex moves. Garchomp / Dragonite offense." },
        { label: "Answer", detail: "Play the chip — force extra switches. Knock Off. Out-bulk the Orb range." },
      ],
      example: { slug: "dragonite", caption: "Life Orb Extreme Speed after Multiscale." },
      examples: [
        { slug: "dragonite", caption: "Life Orb" },
        { slug: "garchomp", caption: "Life Orb breaker" },
        { slug: "ceruledge", caption: "Life Orb / Policy" },
      ],
    },
    {
      title: "Assault Vest",
      tag: "Special wall",
      body: "Sharply boosts Special Defense. You cannot use status, setup, Protect, or pivots that are status moves — only damaging moves. Vest Primarina, Kingambit, and Rillaboom become special anchors that still punch. Physical attacks ignore the Vest.",
      takeaway: "Vest blanks specials and blank status. Hit it physical, or force it out with a physical threat.",
      rows: [
        { label: "Does", detail: "Big SpD boost. Blocks non-damaging moves while held." },
        { label: "When", detail: "Special walls that only need STAB and coverage. Room trucks. Grassy Fake Out still works (damaging)." },
        { label: "Answer", detail: "Physical pressure. Intimidate. Burn. Do not special spam into Vest." },
      ],
      example: { slug: "primarina", caption: "Assault Vest. Special anchor that still Moonblasts." },
      examples: [
        { slug: "primarina", caption: "Assault Vest" },
        { slug: "kingambit", caption: "Vest truck" },
        { slug: "rillaboom", caption: "Vest Grassy" },
        { slug: "archaludon", caption: "Vest Electro Shot" },
      ],
    },
    {
      title: "Rocky Helmet",
      tag: "Contact tax",
      body: "Damages the attacker on contact moves (most physical STABs). Stacks with Rough Skin / Iron Barbs. Corviknight and Garchomp Helmet sets punish U-turn, Fake Out, and physical pivots. Non-contact specials and status shrug it.",
      takeaway: "Helmet punishes contact. Against it: specials, non-contact, or Knock Off.",
      rows: [
        { label: "Does", detail: "Chip on contact hits into the holder." },
        { label: "When", detail: "Physical walls and pivots that expect U-turn / Fake Out / STAB contact." },
        { label: "Answer", detail: "Special attacks. Non-contact moves. Knock Off. Do not U-turn into Helmet for free." },
      ],
      example: { slug: "corviknight", caption: "Rocky Helmet. Contact pays HP." },
      examples: [
        { slug: "corviknight", caption: "Rocky Helmet" },
        { slug: "garchomp", caption: "Helmet Rough Skin" },
        { slug: "toxapex", caption: "Helmet stall" },
      ],
    },
    {
      title: "Heavy-Duty Boots",
      tag: "Hazard ignore",
      body: "Ignores entry hazards — Stealth Rock, spikes, sticky web. Essential on pivots that switch often and on Flying / Fire / Ice types that take huge rock damage. Without Boots, hazard HO turns every pivot into chip hell.",
      takeaway: "Boots enable repeated entry. Against Boots cores: progress with damage, not only rocks.",
      rows: [
        { label: "Does", detail: "No damage or effects from entry hazards on switch-in." },
        { label: "When", detail: "Golisopod, Corvi, Fire types, and any pivot on rock-heavy ladders." },
        { label: "Answer", detail: "Do not rely on rocks alone. Knock Off Boots, then hazard. Direct damage and status." },
      ],
      example: { slug: "golisopod", caption: "Boots First Impression. Exit and re-enter clean." },
      examples: [
        { slug: "golisopod", caption: "Heavy-Duty Boots" },
        { slug: "corviknight", caption: "Boots pivot" },
        { slug: "charizard-mega-y", caption: "Boots / stone — stone wins" },
      ],
    },
    {
      title: "Covert Cloak · Clear Amulet",
      tag: "Deny the tax",
      body: "Covert Cloak blocks additional effects of moves — Fake Out flinch, Thunder Wave from Nuzzle lines, secondary burns and lowers from contact. Clear Amulet blocks Attack drops from Intimidate and Parting Shot. Both are anti-support items on leads and physical wincons.",
      takeaway: "Cloak blanks Fake Out flinch. Amulet blanks Intimidate. Scout which anti-tax they packed.",
      rows: [
        { label: "Does", detail: "Cloak: no secondary effects from moves. Amulet: no Atk drops from abilities/moves." },
        { label: "When", detail: "Leads that must act through Fake Out. Physical cleaners into Incineroar." },
        { label: "Answer", detail: "Against Cloak: raw damage still works — flinch is gone, hit is not. Against Amulet: special pressure or just out-damage." },
      ],
      example: { slug: "garchomp", caption: "Clear Amulet into the cat. Attack stays." },
      examples: [
        { slug: "garchomp", caption: "Clear Amulet" },
        { slug: "whimsicott", caption: "Covert Cloak alt" },
        { slug: "kingambit", caption: "Amulet / Sash lines" },
      ],
    },
    {
      title: "Loaded Dice · Wide Lens",
      tag: "Accuracy tools",
      body: "Loaded Dice makes multi-hit moves (Population Bomb, Scale Shot, Triple Axel) hit more times reliably — Archaludon / Dragonite / Meowscarada lines. Wide Lens pads accuracy on Hurricane, Focus Blast, and other misses. Niche but set-defining when the movepool needs it.",
      takeaway: "Dice is for multi-hit kits. If they have Scale Shot or Triple Axel, expect Dice.",
      rows: [
        { label: "Does", detail: "Dice: better multi-hit counts. Lens: accuracy boost." },
        { label: "When", detail: "Scale Shot Dragonite. Triple Axel Meowscarada. Population Bomb lines." },
        { label: "Answer", detail: "Protect. Resist the type. Do not rely on them missing." },
      ],
      example: { slug: "dragonite", caption: "Loaded Dice Scale Shot under Multiscale." },
      examples: [
        { slug: "dragonite", caption: "Loaded Dice" },
        { slug: "meowscarada", caption: "Dice Triple Axel" },
        { slug: "archaludon", caption: "Dice / Vest lines" },
      ],
    },
    {
      title: "Weakness Policy · White Herb",
      tag: "Trigger items",
      body: "Weakness Policy sharply boosts Attack and SpA when hit by a super-effective move — Ceruledge and setup tanks love the free +2/+2. White Herb cures one stat drop (Shell Smash defense drops, Intimidate once). Both are one-time triggers; Knock Off and careful typing deny them.",
      takeaway: "Do not gift Policy a super-effective hit. Into White Herb Smash: status or priority after the Smash.",
      rows: [
        { label: "Does", detail: "Policy: +2 Atk/SpA on SE hit. Herb: clears one full set of stat drops." },
        { label: "When", detail: "SE bait tanks. Shell Smash users that need defenses back." },
        { label: "Answer", detail: "Hit Policy with neutral damage or status. Knock Off. Revenge Smash after Herb pops." },
      ],
      example: { slug: "ceruledge", caption: "Weakness Policy. SE Fire is a gift." },
      examples: [
        { slug: "ceruledge", caption: "Weakness Policy" },
        { slug: "torkoal", caption: "White Herb Smash" },
        { slug: "garchomp", caption: "Policy / Amulet alts" },
      ],
    },
    {
      title: "Air Balloon",
      tag: "Ground immune",
      body: "Grants Ground immunity until you take damage — then the balloon pops. Gholdengo and frail specials use it to punish predicted Earthquake switch-ins once. After it pops you are a normal Ground target.",
      takeaway: "Pop Balloon with any chip, then Earthquake. Do not lead EQ into a suspected Balloon.",
      rows: [
        { label: "Does", detail: "Ground immunity until damaged once." },
        { label: "When", detail: "Gholdengo and specials into Ground-heavy threes." },
        { label: "Answer", detail: "Any chip pops it. Fake Out. Then Ground. Or hit with non-Ground from the start." },
      ],
      example: { slug: "gholdengo", caption: "Air Balloon. EQ fails once." },
      examples: [{ slug: "gholdengo", caption: "Air Balloon" }],
    },
    {
      title: "Type items · Expert Belt",
      tag: "STAB pad",
      body: "Black Glasses, Charcoal, Miracle Seed, and friends boost one type’s moves. Expert Belt boosts super-effective damage. Quieter than Life Orb or Choice, but common on Kingambit Glasses and coverage specialists. Stacks with STAB for quiet KO numbers.",
      takeaway: "Type items are quiet power. Play the damage ranges as if STAB is hotter than the base kit suggests.",
      rows: [
        { label: "Does", detail: "Boosts one type (glasses/charcoal/…) or all SE hits (Expert Belt)." },
        { label: "When", detail: "Kingambit Black Glasses. Coverage mons that need one type to break." },
        { label: "Answer", detail: "Resist that type. Knock Off. Bulk calcs assume the item until proven otherwise." },
      ],
      example: { slug: "kingambit", caption: "Black Glasses. Dark STAB finishes." },
      examples: [
        { slug: "kingambit", caption: "Black Glasses" },
        { slug: "rillaboom", caption: "Miracle Seed lines" },
        { slug: "cinderace", caption: "Expert Belt / Band" },
      ],
    },
    {
      title: "Mega stone",
      tag: "The wincon slot",
      body: "Holding a Mega stone (Salamencite, Charizardite Y, Garchompite, …) means this Pokémon is your Omni Ring Mega — once per battle. The item slot is the form: Drought Y, Aerilate Mence, raw Mega Chomp. You do not also hold Sitrus. On preview, the stone names the wincon.",
      takeaway: "Mega stone on the list = plan for that Mega until it is gone. The item is the mode.",
      rows: [
        { label: "Does", detail: "Enables Mega Evolution. Item slot is spent on the form." },
        { label: "When", detail: "The three’s closer. Y sun. Mence kite. Mega Lucario plot." },
        { label: "Answer", detail: "Reserve the answer for Mega. Pressure before they Mega. After Mega is down, the stone is a corpse." },
      ],
      example: { slug: "charizard-mega-y", caption: "Charizardite Y. Drought and the nuke." },
      examples: [
        { slug: "charizard-mega-y", caption: "Charizardite Y" },
        { slug: "salamence-mega", caption: "Salamencite" },
        { slug: "garchomp", caption: "Garchompite lines" },
        { slug: "lucario", caption: "Lucarionite" },
      ],
    },
  ],
  examples: [
    { slug: "whimsicott", caption: "Focus Sash" },
    { slug: "corviknight", caption: "Sitrus / Helmet" },
    { slug: "primarina", caption: "Specs / Vest" },
    { slug: "meowscarada", caption: "Choice" },
    { slug: "charizard-mega-y", caption: "Mega stone" },
    { slug: "gholdengo", caption: "Balloon" },
  ],
  viz: "training",
  relatedManuals: [
    "balance-salamence-primarina-aegislash",
    "aggressive-balance-garchomp-primarina-corviknight",
    "balance-garchomp-corviknight-kingambit",
  ],
  next: "speed",
};
