import type { Lesson } from "@/content/curriculum";

export const MOVE_SHEET_LESSONS: Lesson[] = [
  {
    slug: "moves",
    band: "great-ball",
    title: "Moves that steal turns",
    thesis: "Priority jumps the Speed line. Read what it does, when it works, and the answer before you race it.",
    skipIf: "Skip if you already know when not to Sucker Punch into Protect.",
    body: [
      "Read every move in the same order: Does names the effect, When names its live window, and Answer names the counterplay.",
      "Use that frame before the Pokémon name. In Champions 3v3 singles, one stolen turn can decide the whole game.",
    ],
    rules: [
      { label: "+4", detail: "Protect family. Scout and stall." },
      { label: "+3", detail: "Fake Out and Upper Hand. Flinch or punish priority." },
      { label: "+2", detail: "First Impression and Extreme Speed. Lose to +3 and +4." },
      { label: "+1", detail: "Aqua Jet, Ice Shard, Bullet Punch, Shadow Sneak, Accelerock, Grassy Glide." },
      { label: "Sucker", detail: "+1 only into a damaging move. Status, setup, switches, and Protect blank it." },
      { label: "Blank", detail: "Immunity, terrain, Armor Tail, Substitute, and Protect can erase the priority turn." },
    ],
    beats: [
      {
        title: "Fake Out",
        tag: "+3 flinch",
        body: "Fake Out deals light damage at +3 and flinches, but only on the user’s first turn after entering. In singles, that flinch consumes the opponent’s entire turn. Expect it from an opening Incineroar or Rillaboom.",
        takeaway: "Lead Ghost or Armor Tail, or Protect the turn Fake Out would steal your setup. Plan the flinch — do not get surprised.",
        rows: [
          { label: "Does", detail: "+3 Normal damage and flinches — they skip their move." },
          { label: "When", detail: "Lead turn only (once per send). Opens Tailwind, Parting Shot, or a free switch." },
          { label: "Answer", detail: "Ghost immunity, Armor Tail, Protect, or Substitute. Switch on the flinch into your answer." },
        ],
        example: { slug: "incineroar", caption: "Format Fake Out. Then Parting Shot or Blitz." },
        examples: [
          { slug: "incineroar", caption: "Fake Out + Parting Shot" },
          { slug: "rillaboom", caption: "Fake Out under Grassy" },
        ],
      },
      {
        title: "First Impression",
        tag: "+2 nuke",
        body: "First Impression is a high-power Bug attack at +2 priority. It only works on the user’s first turn after entering, so the first send is the danger window. Unlike Fake Out, it aims to take the KO instead of buying a flinch.",
        takeaway: "Protect or resist the first send; pressure freely once First Impression expires.",
        rows: [
          { label: "Does", detail: "Hits hard with Bug damage at +2 priority." },
          { label: "When", detail: "Works only on the user’s first turn after each entry." },
          { label: "Answer", detail: "Protect, resist Bug, or force it to spend the entry turn elsewhere." },
        ],
        example: { slug: "golisopod", caption: "First Impression lead. Exit when chipped." },
        examples: [{ slug: "golisopod", caption: "First Impression + Exit" }],
      },
      {
        title: "Sucker Punch",
        tag: "+1 conditional",
        body: "Sucker Punch attacks at +1 only when the target selected a damaging move. Protect, setup, status, switching, and recovery make it fail. Click it when the opponent must attack to survive the turn.",
        takeaway: "Never Sucker Punch as a coin into Protect. Against their truck: Protect, status, or a faster priority.",
        rows: [
          { label: "Does", detail: "Dark damage at +1 — only if they chose a damaging move." },
          { label: "When", detail: "Revenge after a KO. Finishes a race they already lost on Speed. Kingambit endgame." },
          { label: "Answer", detail: "Protect, status, setup, or switch to make it fail. Faster priority (Fake Out, Extreme Speed) also wins." },
        ],
        example: { slug: "kingambit", caption: "Sucker Punch after the wall is gone." },
        examples: [
          { slug: "kingambit", caption: "Sucker Punch truck" },
          { slug: "absol", caption: "Mega / Sucker lines" },
        ],
      },
      {
        title: "Extreme Speed",
        tag: "+2 Normal",
        body: "Extreme Speed is reliable Normal damage at +2 with no Sucker Punch condition. Use it to finish a faster weakened target. Ghost types are immune and turn the revenge attempt into a lost turn.",
        takeaway: "Click Extreme Speed to secure a visible KO. Ghost blanks it — do not revenge Mimikyu with Normal priority.",
        rows: [
          { label: "Does", detail: "Deals Normal damage at +2 priority." },
          { label: "When", detail: "Finishes a faster target already in KO range — after Multiscale or a Dance." },
          { label: "Answer", detail: "Ghost immunity, Protect, Fake Out first, or chip Multiscale before the Extreme Speed turn." },
        ],
        example: { slug: "dragonite", caption: "Extreme Speed after Multiscale or a Dance." },
        examples: [
          { slug: "dragonite", caption: "Extreme Speed clean" },
          { slug: "arcanine", caption: "Extreme Speed revenge" },
        ],
      },
      {
        title: "Aqua Jet · Ice Shard · Bullet Punch",
        tag: "+1 STAB",
        body: "These are unconditional +1 attacks with different types. Aqua Jet finishes with Water, Ice Shard checks Ice-weak racers, and Bullet Punch punishes Fairy and Ice targets. Their power is modest, so use them to close a known damage range.",
        takeaway: "Click the +1 STAB only for the KO or to cover a Speed loss.",
        rows: [
          { label: "Does", detail: "Deals Water, Ice, or Steel damage at +1 priority." },
          { label: "When", detail: "Finishes a weakened target or patches a lost Speed race." },
          { label: "Answer", detail: "Keep a resist healthy, Protect, or stay outside the KO range." },
        ],
        example: { slug: "basculegion-male", caption: "Aqua Jet if rain dies. Last Respects if it lives." },
        examples: [
          { slug: "basculegion-male", caption: "Aqua Jet" },
          { slug: "mamoswine", caption: "Ice Shard" },
          { slug: "weavile", caption: "Ice Shard / Knock Off" },
          { slug: "scizor", caption: "Bullet Punch" },
        ],
      },
      {
        title: "Shadow Sneak · Accelerock · Grassy Glide",
        tag: "+1 niche",
        body: "Shadow Sneak and Accelerock provide +1 Ghost and Rock damage. Grassy Glide gains priority only while Grassy Terrain is active. Read the type and field before assuming your faster Pokémon moves first.",
        takeaway: "Count Grassy Terrain turns and preserve the resist for the priority type shown.",
        rows: [
          { label: "Does", detail: "Deals typed +1 damage; Grassy Glide needs Grassy Terrain for priority." },
          { label: "When", detail: "Revenge KOs targets weak to Ghost, Rock, or Grass." },
          { label: "Answer", detail: "Use a resist, Protect, overwrite terrain, or stall its remaining turns." },
        ],
        example: { slug: "mimikyu-disguised", caption: "Shadow Sneak after the costume." },
        examples: [
          { slug: "mimikyu-disguised", caption: "Shadow Sneak" },
          { slug: "rillaboom", caption: "Grassy Glide" },
          { slug: "lycanroc-dusk", caption: "Accelerock" },
          { slug: "aegislash-shield", caption: "Shadow Sneak" },
        ],
      },
      {
        title: "Upper Hand",
        tag: "+3 conditional",
        body: "Upper Hand attacks at +3 only if the target chose a priority move. It punishes obvious Fake Out and revenge clicks, then flinches the target. It fails into normal attacks, status, switches, and Protect.",
        takeaway: "Click Upper Hand only into revealed or forced priority.",
        rows: [
          { label: "Does", detail: "Hits and flinches at +3 when the target selected priority." },
          { label: "When", detail: "Punishes forced Fake Out, Sucker Punch, or +1 revenge moves." },
          { label: "Answer", detail: "Use a normal attack, status move, switch, or Protect." },
        ],
        example: { slug: "annihilape", caption: "Upper Hand into the cat when you read Fake Out." },
        examples: [{ slug: "annihilape", caption: "Upper Hand / Rage Fist" }],
      },
      {
        title: "Knock Off",
        tag: "Item tax",
        body: "Knock Off is not priority, but it removes the target’s held item while dealing Dark damage. It is strongest when both a stay and a switch hate losing their item. Do not treat it as an answer to a faster KO.",
        takeaway: "Click Knock Off when every likely target loses lasting value.",
        rows: [
          { label: "Does", detail: "Deals Dark damage and removes a removable held item." },
          { label: "When", detail: "Covers a defensive stay and an item-dependent switch." },
          { label: "Answer", detail: "Absorb it with an expendable item slot or punish the slower click." },
        ],
        example: { slug: "incineroar", caption: "Knock Off + Fake Out is the cat’s tax kit." },
        examples: [
          { slug: "incineroar", caption: "Knock Off" },
          { slug: "meowscarada", caption: "Knock Off coverage" },
          { slug: "weavile", caption: "Knock Off / Ice Shard" },
        ],
      },
    ],
    examples: [
      { slug: "incineroar", caption: "Fake Out" },
      { slug: "golisopod", caption: "First Impression" },
      { slug: "kingambit", caption: "Sucker Punch" },
      { slug: "dragonite", caption: "Extreme Speed" },
      { slug: "basculegion-male", caption: "Aqua Jet" },
      { slug: "mimikyu-disguised", caption: "Shadow Sneak" },
    ],
    viz: "flowchart",
    flowId: "they-fake-out",
    relatedManuals: [
      "balance-salamence-primarina-aegislash",
      "aggressive-balance-garchomp-primarina-corviknight",
      "balance-garchomp-corviknight-kingambit",
    ],
    next: "status-moves",
  },
  {
    slug: "status-moves",
    band: "great-ball",
    title: "Status that buys turns",
    thesis: "Burn cuts Attack. Paralysis cuts Speed. Sleep steals turns. Toxic starts a clock. Taunt shuts the verb.",
    skipIf: "Skip if you already click Wisp and Thunder Wave as covering plays, not chip.",
    body: [
      "Status changes what a Pokémon can do on every turn after the click.",
      "Apply the condition that attacks their job, or use the immunity that makes their status turn fail.",
    ],
    rules: [
      { label: "Burn", detail: "Cuts physical Attack and adds residual damage." },
      { label: "Paralysis", detail: "Cuts Speed and can deny a turn." },
      { label: "Sleep", detail: "Prevents actions until the target wakes." },
      { label: "Poison", detail: "Adds a clock; Toxic damage ramps." },
      { label: "Taunt", detail: "Blocks status, setup, field, and recovery moves." },
    ],
    beats: [
      {
        title: "Burn",
        tag: "½ Attack",
        body: "Burn cuts damage from physical attacks and adds end-of-turn chip. It does not cut Special Attack, so identify the target’s attacking stat first. Will-O-Wisp is strongest when both the active target and its likely physical switch hate the burn.",
        takeaway: "Burn the physical attacker before it starts trading KOs.",
        rows: [
          { label: "Does", detail: "Cuts physical damage and adds residual chip." },
          { label: "When", detail: "Covers a physical stay and a physical switch." },
          { label: "Answer", detail: "Use a Fire type, burn immunity, special attacker, or status cure." },
        ],
        example: { slug: "skeledirge", caption: "Will-O-Wisp covers stay and physical swaps." },
        examples: [
          { slug: "skeledirge", caption: "Will-O-Wisp" },
          { slug: "rotom-wash", caption: "Wisp + Volt Switch" },
          { slug: "ceruledge", caption: "Will-O-Wisp pressure" },
        ],
      },
      {
        title: "Paralysis",
        tag: "Speed cut",
        body: "Paralysis cuts Speed and can deny actions with full paralysis. Use it against the cleaner that wins by moving first. Ground types blank Thunder Wave, so confirm the applying move before switching.",
        takeaway: "Paralyze the Speed wincon before it enters KO range.",
        rows: [
          { label: "Does", detail: "Cuts Speed and adds a chance to lose the turn." },
          { label: "When", detail: "Flips a Speed race your remaining two cannot win." },
          { label: "Answer", detail: "Use immunity to the applying move, a status cure, or priority." },
        ],
        example: { slug: "whimsicott", caption: "Thunder Wave when Tailwind is not the click." },
        examples: [
          { slug: "whimsicott", caption: "Thunder Wave" },
          { slug: "pincurchin", caption: "Thunder Wave support" },
          { slug: "raichu", caption: "Nuzzle / Volt lines" },
        ],
      },
      {
        title: "Sleep",
        tag: "Stolen turns",
        body: "Sleep prevents the target from acting until it wakes. Yawn announces sleep for the next turn and forces a switch or a lost action. Protect the Pokémon that must remain active from the sleep move.",
        takeaway: "Switch on Yawn or absorb sleep with the least-needed slot.",
        rows: [
          { label: "Does", detail: "Stops the target from acting while asleep." },
          { label: "When", detail: "Steals the turn needed to set up, pivot, or take a KO." },
          { label: "Answer", detail: "Use a sleep immunity, avoid powder with Grass, or switch on Yawn." },
        ],
        example: { slug: "slowbro", caption: "Yawn. Stay or sleep next turn." },
        examples: [
          { slug: "slowbro", caption: "Yawn wall" },
          { slug: "whimsicott", caption: "Prankster status pressure" },
          { slug: "banette", caption: "Status / TR support" },
        ],
      },
      {
        title: "Poison and Toxic",
        tag: "Ramp clock",
        body: "Poison adds steady chip, while Toxic damage grows each turn the target stays active. Use Toxic against a wall that plans to recover through normal damage. Steel and Poison types are immune to poison status.",
        takeaway: "Toxic the wall; attack the fragile cleaner.",
        rows: [
          { label: "Does", detail: "Adds residual damage; Toxic ramps each turn." },
          { label: "When", detail: "Forces a recovery wall or repeated pivot onto a timer." },
          { label: "Answer", detail: "Use Steel or Poison immunity, cure status, or end the game quickly." },
        ],
        example: { slug: "glimmora", caption: "Toxic / hazards pressure on HO leads." },
        examples: [
          { slug: "glimmora", caption: "Toxic + rocks" },
          { slug: "toxapex", caption: "Toxic stall" },
          { slug: "noivern", caption: "Toxic / U-turn lines" },
        ],
      },
      {
        title: "Taunt",
        tag: "Shut the verb",
        body: "Taunt blocks non-damaging moves for several turns. Use it before Tailwind, Trick Room, recovery, status, or setup resolves. The target can still attack, and Dark types blank Prankster Taunt.",
        takeaway: "Taunt the setter before attacking it.",
        rows: [
          { label: "Does", detail: "Blocks status, setup, field, and recovery moves." },
          { label: "When", detail: "The opponent needs a non-attacking move to start or survive." },
          { label: "Answer", detail: "Attack, switch, outspeed the Taunt, or use Dark into Prankster." },
        ],
        example: { slug: "whimsicott", caption: "Prankster Taunt into Farigiraf or Cott mirrors." },
        examples: [
          { slug: "whimsicott", caption: "Prankster Taunt" },
          { slug: "grimmsnarl", caption: "Taunt / Screens" },
          { slug: "meowscarada", caption: "Taunt coverage" },
        ],
      },
    ],
    examples: [
      { slug: "skeledirge", caption: "Burn" },
      { slug: "whimsicott", caption: "Para / Taunt" },
      { slug: "slowbro", caption: "Yawn" },
      { slug: "glimmora", caption: "Toxic" },
      { slug: "rotom-wash", caption: "Wisp pivot" },
    ],
    viz: "none",
    relatedManuals: [
      "balance-salamence-primarina-aegislash",
      "aggressive-balance-garchomp-primarina-corviknight",
    ],
    next: "field-moves",
  },
  {
    slug: "field-moves",
    band: "great-ball",
    title: "Weather, terrain, and the board",
    thesis: "Field effects rewrite damage, Speed, priority, and switch costs. Name the setter, the abuser, and the denial line.",
    skipIf: "Skip if you already name the setter on preview and play overwrite.",
    body: [
      "Weather and terrain usually start on entry; Tailwind, Trick Room, and hazards spend a turn.",
      "Count the field turns and preserve the Pokémon that denies or outlasts the package.",
    ],
    rules: [
      { label: "Rain", detail: "Water up, Fire down, and rain abilities activate." },
      { label: "Sun", detail: "Fire up, Water down, and sun abilities activate." },
      { label: "Terrain", detail: "Changes recovery, priority, status, or move power." },
      { label: "Tailwind", detail: "Doubles the user’s side Speed for a short clock." },
      { label: "Trick Room", detail: "Makes slower Pokémon act first within their priority bracket." },
      { label: "Hazards", detail: "Tax switches and break Sash or Multiscale." },
    ],
    beats: [
      {
        title: "Rain",
        tag: "Weather",
        body: "Rain strengthens Water, weakens Fire, and enables rain-specific moves and abilities. Pelipper sets it on entry, so the board changes before either side clicks. Overwrite rain or stall its turns before fighting the boosted cleaner.",
        takeaway: "Preserve the rain answer and count every turn after Pelipper enters.",
        rows: [
          { label: "Does", detail: "Boosts Water, weakens Fire, and activates rain payoffs." },
          { label: "When", detail: "Starts on Pelipper’s entry or a Rain Dance turn." },
          { label: "Answer", detail: "Overwrite weather, stall turns, or keep a Water resist healthy." },
        ],
        example: { slug: "pelipper", caption: "Drizzle on entry. The field is the team." },
        examples: [
          { slug: "pelipper", caption: "Drizzle" },
          { slug: "basculegion-male", caption: "Swift Swim" },
          { slug: "archaludon", caption: "Electro Shot" },
        ],
      },
      {
        title: "Sun",
        tag: "Weather",
        body: "Sun strengthens Fire, weakens Water, and activates Chlorophyll and stronger Growth. Torkoal and Mega Charizard Y set it on entry. Deny the setter or overwrite sun before the Fire nuke takes the free KO.",
        takeaway: "Treat Mega Charizard Y as both the setter and the immediate attacker.",
        rows: [
          { label: "Does", detail: "Boosts Fire, weakens Water, and activates sun payoffs." },
          { label: "When", detail: "Starts on Torkoal or Mega Charizard Y entry." },
          { label: "Answer", detail: "Overwrite weather, use a Fire resist, or pressure with Rock damage." },
        ],
        example: { slug: "charizard-mega-y", caption: "Drought Mega. Field and nuke." },
        examples: [
          { slug: "charizard-mega-y", caption: "Drought" },
          { slug: "torkoal", caption: "Drought support" },
          { slug: "venusaur", caption: "Chlorophyll / Growth" },
        ],
      },
      {
        title: "Grassy Terrain",
        tag: "Terrain",
        body: "Grassy Terrain heals grounded Pokémon, weakens Earthquake, and gives Grassy Glide priority. Rillaboom sets it on entry. Remove Rillaboom, overwrite the terrain, or stall before racing Glide.",
        takeaway: "Never Speed-race Grassy Glide while terrain is active.",
        rows: [
          { label: "Does", detail: "Heals grounded Pokémon, softens Earthquake, and enables priority Glide." },
          { label: "When", detail: "Starts when Grassy Surge Rillaboom enters." },
          { label: "Answer", detail: "Overwrite terrain, stall its turns, or use a Grass resist." },
        ],
        example: { slug: "rillaboom", caption: "Grassy Surge. Fake Out. Wood Hammer." },
        examples: [
          { slug: "rillaboom", caption: "Grassy Surge" },
          { slug: "sneasler", caption: "Unburden under terrain" },
          { slug: "armarouge", caption: "Terrain offense seat" },
        ],
      },
      {
        title: "Tailwind",
        tag: "Speed clock",
        body: "Tailwind doubles Speed for the user’s side on a short clock. The setup turn counts, so the setter must hand the remaining turns to a cleaner quickly. Fake Out, Taunt, or stalling the clock denies the plan.",
        takeaway: "Set Tailwind only when the next Pokémon immediately cashes the Speed.",
        rows: [
          { label: "Does", detail: "Doubles the user’s side Speed for a limited number of turns." },
          { label: "When", detail: "Flips multiple losing Speed matchups for the next attacker." },
          { label: "Answer", detail: "Fake Out or Taunt the setter, use priority, or stall the clock." },
        ],
        example: { slug: "whimsicott", caption: "Prankster Tailwind. Then switch." },
        examples: [
          { slug: "whimsicott", caption: "Tailwind" },
          { slug: "noivern", caption: "Tailwind / pivot" },
          { slug: "garchomp", caption: "Often inherits the clock" },
        ],
      },
      {
        title: "Trick Room",
        tag: "Slow first",
        body: "Trick Room makes slower Pokémon move first within the same priority bracket. The setup turn counts, and priority still ignores the reversed Speed order. Stop the setter or spend the clock protecting and switching.",
        takeaway: "Taunt Trick Room before it resolves; use priority or stall if it goes up.",
        rows: [
          { label: "Does", detail: "Reverses normal Speed order within each priority bracket." },
          { label: "When", detail: "Lets slow attackers move before faster teams for a short clock." },
          { label: "Answer", detail: "Taunt the setter, use priority, or stall turns with Protect and switches." },
        ],
        example: { slug: "farigiraf", caption: "The setter. Plan as if it must appear." },
        examples: [
          { slug: "farigiraf", caption: "Trick Room" },
          { slug: "kingambit", caption: "Room truck" },
          { slug: "annihilape", caption: "Rage Fist under Room" },
          { slug: "indeedee-female", caption: "Terrain / Room support" },
        ],
      },
      {
        title: "Stealth Rock and spikes",
        tag: "Hazards",
        body: "Stealth Rock and Spikes damage Pokémon when they switch in. That tax breaks Focus Sash and Multiscale before the attack lands. Set hazards when the opponent must pivot repeatedly; clear them when your win condition depends on full HP.",
        takeaway: "Clear hazards before sending a Sash or Multiscale win condition.",
        rows: [
          { label: "Does", detail: "Taxes switch-ins and breaks full-HP effects." },
          { label: "When", detail: "Punishes teams forced to pivot several times." },
          { label: "Answer", detail: "Use Rapid Spin, Defog, or Mortal Spin; stop unnecessary switches." },
        ],
        example: { slug: "glimmora", caption: "Sash hazards lead on HO." },
        examples: [
          { slug: "glimmora", caption: "Stealth Rock" },
          { slug: "mamoswine", caption: "Stealth Rock pressure" },
          { slug: "excadrill", caption: "Rocks / Spin" },
        ],
      },
    ],
    examples: [
      { slug: "pelipper", caption: "Rain" },
      { slug: "charizard-mega-y", caption: "Sun" },
      { slug: "rillaboom", caption: "Grassy" },
      { slug: "whimsicott", caption: "Tailwind" },
      { slug: "farigiraf", caption: "Trick Room" },
      { slug: "glimmora", caption: "Rocks" },
    ],
    viz: "none",
    relatedManuals: [
      "balance-salamence-primarina-aegislash",
      "aggressive-balance-garchomp-primarina-corviknight",
    ],
    next: "boost-moves",
  },
  {
    slug: "boost-moves",
    band: "great-ball",
    title: "Boosts and debuffs",
    thesis: "Boost only from a free turn. Debuff only when the next Pokémon cashes it. Keep a reset for the stack.",
    skipIf: "Skip if you already refuse to Dance into Unaware and Protect.",
    body: [
      "Setup converts one safe turn into stronger later turns; a bad setup click donates damage.",
      "Identify the free turn, the revenge answer, and the reset before committing.",
    ],
    rules: [
      { label: "+2 Attack", detail: "Swords Dance turns physical pressure into immediate KO ranges." },
      { label: "Speed + Attack", detail: "Dragon Dance and Shift Gear flip the next race." },
      { label: "Special", detail: "Nasty Plot, Calm Mind, and Quiver Dance build special pressure." },
      { label: "Mixed", detail: "Shell Smash, Growth, and Bulk Up trade different risks for stages." },
      { label: "Debuff", detail: "Parting Shot, Screech, and Charm create a partner’s turn." },
      { label: "Reset", detail: "Clear Smog and Haze erase stages; Unaware ignores key boosts." },
    ],
    beats: [
      {
        title: "Swords Dance",
        tag: "+2 Attack",
        body: "Swords Dance raises Attack by two stages and turns physical hits into KO threats. Click it behind Disguise, after a forced switch, or when the opponent cannot threaten meaningful damage. Do not donate the setup turn to burn, Taunt, or a reset.",
        takeaway: "Click Swords Dance only when you can name the free turn and the next KO.",
        rows: [
          { label: "Does", detail: "Raises Attack by two stages." },
          { label: "When", detail: "Cashes Disguise, a forced switch, weak damage, or a secured free turn." },
          { label: "Answer", detail: "Burn, Taunt, revenge with priority, reset stages, or use Unaware." },
        ],
        example: { slug: "mimikyu-disguised", caption: "Costume, then Swords Dance." },
        examples: [
          { slug: "mimikyu-disguised", caption: "Disguise Dance" },
          { slug: "kingambit", caption: "Dance after KO" },
          { slug: "gyarados", caption: "Intimidate Dance" },
        ],
      },
      {
        title: "Dragon Dance · Shift Gear",
        tag: "Speed + Attack",
        body: "Dragon Dance raises Attack and Speed; Shift Gear adds an even larger Speed jump. One click can flip both damage ranges and the next race. Deny the free turn or keep priority ready.",
        takeaway: "Dance when one boost outspeeds every remaining answer.",
        rows: [
          { label: "Does", detail: "Raises Attack and Speed; Shift Gear raises Speed further." },
          { label: "When", detail: "One boost converts the user into the fastest remaining attacker." },
          { label: "Answer", detail: "Taunt, burn, use priority, phaze, reset stages, or use Unaware." },
        ],
        example: { slug: "dragonite", caption: "Dragon Dance into Extreme Speed clean." },
        examples: [
          { slug: "dragonite", caption: "Dragon Dance" },
          { slug: "baxcalibur", caption: "Dragon Dance breaker" },
          { slug: "gyarados", caption: "Dragon Dance" },
        ],
      },
      {
        title: "Nasty Plot · Calm Mind · Quiver Dance",
        tag: "Special stack",
        body: "Nasty Plot sharply raises Special Attack, Calm Mind adds special bulk, and Quiver Dance also raises Speed. Match the move to the race: Plot breaks now, Calm Mind survives special trades, and Quiver Dance sweeps after one safe turn. Stop the first click before the stack compounds.",
        takeaway: "Use the special boost only when its added stat wins the next exchange.",
        rows: [
          { label: "Does", detail: "Raises Special Attack, with bulk or Speed depending on the move." },
          { label: "When", detail: "Breaks a wall, survives a special trade, or flips a Speed race." },
          { label: "Answer", detail: "Taunt, use strong physical pressure, reset stages, or use Unaware." },
        ],
        example: { slug: "armarouge", caption: "Special setup before the Expanding Force push." },
        examples: [
          { slug: "armarouge", caption: "Special setup seat" },
          { slug: "primarina", caption: "Calm Mind" },
          { slug: "gholdengo", caption: "Nasty Plot lines" },
          { slug: "chandelure", caption: "Special Fire stack" },
        ],
      },
      {
        title: "Shell Smash · Growth · Bulk Up",
        tag: "All-in / bulk",
        body: "Shell Smash trades defenses for major offense and Speed, Growth spikes harder in sun, and Bulk Up raises Attack with physical bulk. Each move needs a different free turn and payoff. Attack the exposed defense or remove the field before the boost becomes a sweep.",
        takeaway: "Pick the boost that immediately converts the board state into a KO or a live.",
        rows: [
          { label: "Does", detail: "Builds mixed offense, sun offense, or physical offense plus bulk." },
          { label: "When", detail: "Cashes a safe turn, active sun, or a physical matchup it can wall." },
          { label: "Answer", detail: "Use priority, Taunt, field overwrite, special pressure, or a stage reset." },
        ],
        example: { slug: "venusaur", caption: "Growth in sun. Chlorophyll cashes Drought." },
        examples: [
          { slug: "venusaur", caption: "Growth in sun" },
          { slug: "annihilape", caption: "Bulk Up" },
          { slug: "torkoal", caption: "Shell Smash / Drought lines" },
        ],
      },
      {
        title: "Parting Shot · Screech · Charm",
        tag: "Debuff",
        body: "Parting Shot lowers both offenses and pivots, Screech drops Defense, and Charm sharply drops Attack. These moves matter only when the reduced stat creates a safe entry or a KO. Bring the partner in immediately instead of wasting the temporary advantage.",
        takeaway: "Debuff only when the next slot is ready to cash the drop.",
        rows: [
          { label: "Does", detail: "Lowers offense or defense; Parting Shot also switches the user out." },
          { label: "When", detail: "Creates a safe entry or puts the target into the partner’s KO range." },
          { label: "Answer", detail: "Switch to clear drops, use Clear Body, or punish the low-damage turn." },
        ],
        example: { slug: "incineroar", caption: "Parting Shot into the cleaner." },
        examples: [
          { slug: "incineroar", caption: "Parting Shot" },
          { slug: "grimmsnarl", caption: "Support debuffs" },
          { slug: "whimsicott", caption: "Charm lines" },
        ],
      },
      {
        title: "Clear Smog · Haze · Unaware",
        tag: "Reset",
        body: "Clear Smog and Haze erase accumulated stat stages. Unaware ignores relevant opposing boosts while calculating damage, turning many setup lines into wasted turns. Reveal the reset early enough that the booster cannot take two KOs first.",
        takeaway: "Bring the reset on the first setup turn, not after the sweep starts.",
        rows: [
          { label: "Does", detail: "Erases stages or ignores the opponent’s boosted damage and defenses." },
          { label: "When", detail: "Stops a setup attacker before its stages decide the game." },
          { label: "Answer", detail: "Attack the reset user directly, Taunt it, or win without stacking stages." },
        ],
        example: { slug: "skeledirge", caption: "Unaware. Dance dies here." },
        examples: [
          { slug: "skeledirge", caption: "Unaware" },
          { slug: "dondozo", caption: "Unaware wall" },
          { slug: "toxapex", caption: "Haze / Toxic reset" },
        ],
      },
    ],
    examples: [
      { slug: "mimikyu-disguised", caption: "Swords Dance" },
      { slug: "dragonite", caption: "Dragon Dance" },
      { slug: "armarouge", caption: "Special setup" },
      { slug: "incineroar", caption: "Parting Shot" },
      { slug: "skeledirge", caption: "Unaware reset" },
    ],
    viz: "none",
    relatedManuals: [
      "balance-salamence-primarina-aegislash",
      "balance-garchomp-corviknight-kingambit",
    ],
    next: "pivot-moves",
  },
  {
    slug: "pivot-moves",
    band: "great-ball",
    title: "Pivots that keep momentum",
    thesis: "Pivots act before leaving. Use them when staying and switching both preserve your advantage.",
    skipIf: "Skip if you already pivot when stay and swap both need an answer.",
    body: [
      "A hard switch gives the opponent a free action; a pivot deals damage or applies a debuff first.",
      "Choose the pivot whose immunity and contact risks do not turn your momentum into a blank turn.",
    ],
    rules: [
      { label: "U-turn", detail: "Bug damage, then switch." },
      { label: "Volt Switch", detail: "Electric damage, then switch; Ground blocks it." },
      { label: "Flip Turn", detail: "Water damage, then switch." },
      { label: "Parting Shot", detail: "Lowers both offenses, then switches." },
      { label: "Teleport", detail: "Slow switch that brings the next slot in safely." },
      { label: "Exit", detail: "Shed Tail passes protection; Emergency Exit forces a switch at half HP." },
    ],
    beats: [
      {
        title: "U-turn",
        tag: "Bug pivot",
        body: "U-turn deals Bug damage and switches the user out after the hit. It covers a stay with chip and a switch with your chosen answer. Click it when the opponent has two likely responses that require different attackers.",
        takeaway: "U-turn when both stay and switch improve your matchup.",
        rows: [
          { label: "Does", detail: "Deals Bug damage, then lets the user switch." },
          { label: "When", detail: "Covers both an uncertain stay and an uncertain switch." },
          { label: "Answer", detail: "Use a Bug resist, punish contact, or set hazards to tax the pivot cycle." },
        ],
        example: { slug: "meowscarada", caption: "U-turn covers stay and swap." },
        examples: [
          { slug: "meowscarada", caption: "Covering U-turn" },
          { slug: "corviknight", caption: "Shield U-turn" },
          { slug: "scizor", caption: "U-turn / Bullet Punch" },
        ],
      },
      {
        title: "Volt Switch",
        tag: "Electric pivot",
        body: "Volt Switch deals Electric damage and leaves after connecting. Ground immunity blocks the damage and the switch, so preview the opponent’s Ground slot before clicking. Use it to maintain pressure against Water and Flying targets.",
        takeaway: "Never autopilot Volt Switch while a Ground immunity is alive.",
        rows: [
          { label: "Does", detail: "Deals Electric damage, then switches after a successful hit." },
          { label: "When", detail: "Pressures Water or Flying targets without hard switching." },
          { label: "Answer", detail: "Send a Ground immunity or punish the expected incoming partner." },
        ],
        example: { slug: "rotom-wash", caption: "Volt Switch + Will-O-Wisp." },
        examples: [
          { slug: "rotom-wash", caption: "Volt Switch" },
          { slug: "raichu", caption: "Volt Switch race" },
          { slug: "pincurchin", caption: "Electric support pivot" },
        ],
      },
      {
        title: "Flip Turn",
        tag: "Water pivot",
        body: "Flip Turn deals Water damage and switches the user out after connecting. Rain boosts the chip, but the move still keeps momentum without rain. Use it when the Water user attracts a predictable resist.",
        takeaway: "Flip Turn into the Water resist, then bring the matchup that punishes it.",
        rows: [
          { label: "Does", detail: "Deals Water damage, then lets the user switch." },
          { label: "When", detail: "Baits a Water resist and brings in its direct answer." },
          { label: "Answer", detail: "Use Water immunity or punish the incoming partner with hazards and pressure." },
        ],
        example: { slug: "basculegion-male", caption: "Flip Turn under rain. Keep the race." },
        examples: [
          { slug: "basculegion-male", caption: "Flip Turn" },
          { slug: "swampert", caption: "Flip Turn / EQ" },
          { slug: "pelipper", caption: "Sets the rain they pivot under" },
        ],
      },
      {
        title: "Parting Shot",
        tag: "Debuff pivot",
        body: "Parting Shot lowers the target’s Attack and Special Attack, then switches the user. It creates a safer entry without dealing damage. Click it when a cleaner can use the reduced threat immediately.",
        takeaway: "Parting Shot directly into the setup Pokémon that cashes the drop.",
        rows: [
          { label: "Does", detail: "Lowers both offenses by one stage, then switches the user." },
          { label: "When", detail: "Creates a safe entry for setup or preserves a weakened support." },
          { label: "Answer", detail: "Switch to clear drops, block stat loss, or punish the non-damaging turn." },
        ],
        example: { slug: "incineroar", caption: "Fake Out, tax, Parting Shot." },
        examples: [{ slug: "incineroar", caption: "Parting Shot" }],
      },
      {
        title: "Teleport · Shed Tail · Emergency Exit",
        tag: "Forced leave",
        body: "Teleport moves slowly to bring the next Pokémon in after the opponent acts. Shed Tail spends HP to pass a Substitute, while Emergency Exit forces Golisopod out when its HP crosses half. Track HP and switch order before using or triggering these effects.",
        takeaway: "Use the delayed or forced switch to give the win condition a safe entry.",
        rows: [
          { label: "Does", detail: "Creates a slow switch, passes a Substitute, or forces an HP-triggered exit." },
          { label: "When", detail: "Brings the next slot in safely or converts lost HP into position." },
          { label: "Answer", detail: "Set hazards, break the Substitute, or control the damage that triggers Exit." },
        ],
        example: { slug: "golisopod", caption: "First Impression, then Exit at half." },
        examples: [
          { slug: "golisopod", caption: "Emergency Exit" },
          { slug: "cyclizar", caption: "Shed Tail" },
          { slug: "slowbro", caption: "Teleport wall" },
        ],
      },
    ],
    examples: [
      { slug: "meowscarada", caption: "U-turn" },
      { slug: "rotom-wash", caption: "Volt Switch" },
      { slug: "incineroar", caption: "Parting Shot" },
      { slug: "basculegion-male", caption: "Flip Turn" },
      { slug: "golisopod", caption: "Emergency Exit" },
      { slug: "corviknight", caption: "U-turn shield" },
    ],
    viz: "none",
    relatedManuals: [
      "aggressive-balance-garchomp-primarina-corviknight",
      "balance-garchomp-corviknight-kingambit",
    ],
    next: "defense-moves",
  },
  {
    slug: "defense-moves",
    band: "great-ball",
    title: "Defense that denies the turn",
    thesis: "Defense wins by denying the opponent’s chosen turn. Ask the question, punish the answer, then stop stalling.",
    skipIf: "Skip if you already Protect to ask a question, not to farm HP.",
    body: [
      "Defensive moves scout, block, lock, heal, or reduce damage instead of taking a KO.",
      "Use each denial move to create the next attacking turn, not to extend a losing position.",
    ],
    rules: [
      { label: "Protect", detail: "+4 scout that blocks most attacks for one turn." },
      { label: "Substitute", detail: "Trades HP for a barrier against damage and status." },
      { label: "Encore", detail: "Forces repetition of the last move." },
      { label: "Recover", detail: "Keeps a required wall in the matchup." },
      { label: "Screens", detail: "Reduce physical, special, or both damage categories." },
      { label: "Disable", detail: "Removes a key move or shared option." },
    ],
    beats: [
      {
        title: "Protect",
        tag: "+4 scout",
        body: "Protect acts at +4 and blocks most direct effects for the turn. Use it to reveal coverage, stall Sucker Punch, or spend a field turn. Repeated Protect can fail, and passive opponents can use the free turn to switch or set up.",
        takeaway: "Protect once to learn or stall something specific, then act on the answer.",
        rows: [
          { label: "Does", detail: "Blocks most attacks and effects for one turn at +4 priority." },
          { label: "When", detail: "Scouts coverage, stalls Sucker Punch, or burns a field turn." },
          { label: "Answer", detail: "Set up, switch, use a bypass, or punish the likely move after Protect." },
        ],
        example: { slug: "garchomp", caption: "Protect into Ice or Fairy is information." },
        examples: [
          { slug: "garchomp", caption: "Protect scout" },
          { slug: "kingambit", caption: "Protect vs revenge" },
          { slug: "dragonite", caption: "Protect Multiscale" },
        ],
      },
      {
        title: "Substitute",
        tag: "HP → doll",
        body: "Substitute spends HP to create a barrier that absorbs damage and blocks many status moves. Use it on a forced switch or an expected status click. A strong attack breaks it and turns the HP cost into a loss.",
        takeaway: "Substitute into status or a forced switch, never into obvious heavy damage.",
        rows: [
          { label: "Does", detail: "Spends HP to create a barrier against damage and many status moves." },
          { label: "When", detail: "Punishes an expected status move, switch, or weak attack." },
          { label: "Answer", detail: "Break it immediately with strong damage or a move that bypasses it." },
        ],
        example: { slug: "mimikyu-disguised", caption: "Sub / Dance lines after costume." },
        examples: [
          { slug: "greninja", caption: "Sub pressure" },
          { slug: "meowscarada", caption: "Sub / U-turn" },
          { slug: "dragonite", caption: "Sub / Dance" },
        ],
      },
      {
        title: "Encore",
        tag: "Lock the click",
        body: "Encore forces the target to repeat its last move for several turns. Lock Protect, setup, recovery, or weak coverage to create a free switch or setup turn. Do not Encore an attack that still wins the matchup.",
        takeaway: "Encore the non-damaging mistake, then cash the forced repetition immediately.",
        rows: [
          { label: "Does", detail: "Forces the target to repeat its last selected move." },
          { label: "When", detail: "Punishes Protect, setup, recovery, status, or weak coverage." },
          { label: "Answer", detail: "Switch out, attack before the lock, or use Dark against Prankster Encore." },
        ],
        example: { slug: "whimsicott", caption: "Prankster Encore into Protect." },
        examples: [
          { slug: "whimsicott", caption: "Encore" },
          { slug: "grimmsnarl", caption: "Encore / Screens" },
          { slug: "banette", caption: "Encore / TR support" },
        ],
      },
      {
        title: "Roost · Slack Off · Recover",
        tag: "Stay in slot",
        body: "Recovery restores HP and keeps a required defensive Pokémon in the matchup. Click it when you survive the next hit and the healed HP preserves a future answer. Taunt, Toxic, setup, or a stronger hit punishes blind recovery.",
        takeaway: "Recover only when the restored HP preserves a specific matchup.",
        rows: [
          { label: "Does", detail: "Restores HP so the user can keep checking a threat." },
          { label: "When", detail: "The user survives the turn and needs HP for a later answer." },
          { label: "Answer", detail: "Taunt, Toxic, boost, or apply enough damage to deny the heal loop." },
        ],
        example: { slug: "corviknight", caption: "Roost. The shield stays in the slot." },
        examples: [
          { slug: "corviknight", caption: "Roost" },
          { slug: "skeledirge", caption: "Slack Off" },
          { slug: "clefable", caption: "Recovery / Wish" },
        ],
      },
      {
        title: "Reflect · Light Screen · Aurora Veil",
        tag: "Screens",
        body: "Reflect cuts physical damage, Light Screen cuts special damage, and Aurora Veil cuts both under snow. Screens buy safer setup and extra lives for the remaining team. Remove the setter, stall the turns, or attack from the uncovered category.",
        takeaway: "Set the screen that lets the next win condition survive its answer.",
        rows: [
          { label: "Does", detail: "Reduces physical, special, or both damage categories for several turns." },
          { label: "When", detail: "Creates a setup turn or lets a cleaner survive revenge damage." },
          { label: "Answer", detail: "Stall turns, remove screens, Taunt the setter, or hit the uncovered side." },
        ],
        example: { slug: "grimmsnarl", caption: "Prankster screens. Then the truck." },
        examples: [
          { slug: "grimmsnarl", caption: "Screens" },
          { slug: "ninetales-alola", caption: "Aurora Veil" },
          { slug: "klefki", caption: "Screens support" },
        ],
      },
      {
        title: "Disable · Spite · Imprison",
        tag: "Shut one verb",
        body: "Disable blocks the last used move, Spite drains its PP, and Imprison blocks moves shared with the user. Use them when one coverage or utility move controls the matchup. Switch moves or leave the matchup instead of feeding the lock.",
        takeaway: "Disable the one move that beats your position, then attack before they reset.",
        rows: [
          { label: "Does", detail: "Blocks or drains a specific move instead of locking every action." },
          { label: "When", detail: "One coverage, recovery, or field move controls the matchup." },
          { label: "Answer", detail: "Switch out, choose another move, or pressure before the denial lands." },
        ],
        example: { slug: "indeedee-female", caption: "Psychic support with Imprison lines." },
        examples: [
          { slug: "indeedee-female", caption: "Imprison / terrain" },
          { slug: "banette", caption: "Disable / Destiny Bond" },
          { slug: "klefki", caption: "Disrupt support" },
        ],
      },
    ],
    examples: [
      { slug: "garchomp", caption: "Protect" },
      { slug: "whimsicott", caption: "Encore" },
      { slug: "corviknight", caption: "Roost" },
      { slug: "grimmsnarl", caption: "Screens" },
      { slug: "mimikyu-disguised", caption: "Substitute" },
    ],
    viz: "none",
    relatedManuals: [
      "balance-salamence-primarina-aegislash",
      "aggressive-balance-garchomp-primarina-corviknight",
      "balance-garchomp-corviknight-kingambit",
    ],
    next: "training",
  },
];
